server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medi_reserve?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

jwt:
  secret: "your-256-bit-secret-key-must-be-long-enough-1234567890"
  expiration: 7200000
  interceptor:
    enabled: true
    exclude-paths:
      - /auth/login
      - /auth/register
      - /test/ping
      - /error
      - /doc.html
      - /webjars/**
      - /v3/api-docs/**
      - /swagger-ui/**

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.medireserve.common.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl