server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medi_reserve?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

jwt:
  secret: "your-256-bit-secret-key-must-be-long-enough-1234567890"
  expiration: 7200000
  interceptor:
    enabled: true
    exclude-paths:
      - /doctor/login
      - /doctor/register
      - /doc.html
      - /css/**
      - /js/**
      - /favicon.ico
      - /webjars/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /error

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 医生端
      packages-to-scan: com.medireserve.doctor.controller
      paths-to-match: '/**'

# knife4j基础配置
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.medireserve.common.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl